site_name: Fortes Knowledge Base
site_url: https://milanozinga.github.io/fortes-kb-poc/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - content.action.edit
    - navigation.tabs
    - navigation.sections
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.tabs
    - content.action.share
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - navigation.language   # <- Deze toevoegen!
  logo: images/logo.png
  palette:
    - scheme: default
      primary: '#2AACE2'
      accent: '#FAA81C'
    - scheme: slate
      primary: '#182A54'
      accent: '#2AACE2'

extra_css:
  - custom-code/extra.css

extra_javascript:
  - custom-code/extra.js

plugins:
  - i18n:
      default_language: nl
      languages:
        - locale: nl
          name: Nederlands
          build: true
          default: true
        - locale: en
          name: English
          build: true
        - locale: de
          name: Duits
          build: true
  - search


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
