name: Build and Deploy Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install mkdocs-material mike

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages || true

      - name: Build and deploy documentation
        run: |
          mike deploy 1.0 latest --push --update-aliases
          mike set-default 1.0 --push
